QLSach/QLSach/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using QLSach.Models;
using QLSach.ViewsModels;


namespace QLSach.Controllers
{
   
        public class BooksController : Controller
        {
            private readonly AppDbContext _appDbContext;
            private readonly IWebHostEnvironment _webHostEnvironment;

            public BooksController(AppDbContext appDbContext, IWebHostEnvironment webHostEnvironment)
            {
                _appDbContext = appDbContext;
                _webHostEnvironment = webHostEnvironment;
            }
            public IActionResult Index()
            {
                ViewBag.Message = "Quản lý sách";

                

                var products = _appDbContext.Books.Include(p => p.Category).ToList();

                return View(products);
            }

            public IActionResult Create()
            {
                BooksCreateVM booksVM = new BooksCreateVM()
                {
                    Books = new Books(),
                    CategorySelectList = _appDbContext.Categories.Select(item => new SelectListItem
                    {
                        Text = item.CategoryName,
                        Value = item.Id.ToString()
                    })
                };

                return View(booksVM);
            }

            [HttpPost]
            public IActionResult Create(BooksCreateVM booksCreateVM)
            {
            if (ModelState.IsValid)
            {

                _appDbContext.Books.Add(booksCreateVM.Books);
                _appDbContext.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(booksCreateVM);
        }

        public IActionResult Edit(int? id)
        {
            BooksCreateVM booksVM = new BooksCreateVM()
            {
                Books = _appDbContext.Books.Find(id),
                CategorySelectList = _appDbContext.Categories.Select(item => new SelectListItem
                {
                    Text = item.CategoryName,
                    Value = item.Id.ToString()
                })
            };

            return View(booksVM);
        }

        [HttpPost]
        public IActionResult Edit(BooksCreateVM booksCreateVM)
        {

            if (ModelState.IsValid)
            {
                _appDbContext.Books.Update(booksCreateVM.Books);
                _appDbContext.SaveChanges();

                 return RedirectToAction("Index");
            }




            return RedirectToAction("booksCreateVM");
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var books = _appDbContext.Books.Find(id);
            if (books == null) return NotFound();

            return View(books);
        }

        [HttpPost]
        public IActionResult DeleteProduct(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var books = _appDbContext.Books.Find(id);
            if (books == null) return NotFound();

            _appDbContext.Books.Remove(books);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

QLSach/QLSach/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QLSach.Models;

namespace QLSach.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _appDbContext;
        public CategoryController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }
        public IActionResult Index()
        {
            IEnumerable<Category> categories = _appDbContext.Categories.Include(p => p.Books);
            return View(categories);
        }
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Categories.Add(category);
                _appDbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(category);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _appDbContext.Categories.Find(id);
            if (category == null) return NotFound();

            return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Categories.Update(category);
                _appDbContext.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(category);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _appDbContext.Categories.Find(id);
            if (category == null) return NotFound();

            return View(category);
        }

        [HttpPost]
        public IActionResult DeleteCategory(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = _appDbContext.Categories.Find(id);
            if (category == null) return NotFound();

            _appDbContext.Categories.Remove(category);
            _appDbContext.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

QLSach/QLSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Environmental</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/css/owl.carousel.min.css">
    <link rel="stylesheet" href="/assets/css/slicknav.css">
    <link rel="stylesheet" href="/assets/css/flaticon.css">
    <link rel="stylesheet" href="/assets/css/progressbar_barfiller.css">
    <link rel="stylesheet" href="/assets/css/gijgo.css">
    <link rel="stylesheet" href="/assets/css/animate.min.css">
    <link rel="stylesheet" href="/assets/css/animated-headline.css">
    <link rel="stylesheet" href="/assets/css/magnific-popup.css">
    <link rel="stylesheet" href="/assets/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="/assets/css/themify-icons.css">
    <link rel="stylesheet" href="/assets/css/slick.css">
    <link rel="stylesheet" href="/assets/css/nice-select.css">
    <link rel="stylesheet" href="/assets/css/style.css">
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="/assets/img/logo/loder.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area">
            <div class="main-header ">
                <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-2">
                                <div class="logo">
                                    <a href="index.html"><img src="/assets/img/logo/logo.png" alt=""></a>
                                </div>
                            </div>
                            <div class="col-xl-10 col-lg-10">
                                <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                                    <!-- Main-menu -->
                                    <div class="main-menu d-none d-lg-block">
                                        <nav>
                                            <ul id="navigation">
                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Admin</a></li>
                                                
                                            </ul>
                                        </nav>
                                    </div>
                                    <!-- Header-btn -->
                                    
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer>
        <div class="footer-wrapper">
            <!-- Footer Start-->
            <div class="footer-area footer-padding">
                <div class="container ">
                    <div class="row justify-content-between">
                        <div class="col-xl-4 col-lg-3 col-md-8 col-sm-8">
                            <div class="single-footer-caption mb-50">
                                <div class="single-footer-caption mb-30">
                                    <!-- logo -->
                                    <div class="footer-logo mb-35">
                                        <a href="index.html"><img src="/assets/img/logo/logo2_footer.png" alt=""></a>
                                    </div>
                                    <div class="footer-tittle">
                                        <div class="footer-pera">
                                            <p>The automated process starts as soon as your clothes go into the machine.</p>
                                        </div>
                                    </div>
                                    <!-- social -->
                                    <div class="footer-social">
                                        <a href="#"><i class="fab fa-twitter"></i></a>
                                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                                        <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-3 col-md-4 col-sm-4">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Our solutions</h4>
                                    <ul>
                                        <li><a href="#">Design & creatives</a></li>
                                        <li><a href="#">Telecommunication</a></li>
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-4 col-sm-4">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Company</h4>
                                    <ul>
                                        <li><a href="#">About</a></li>
                                        <li><a href="#">Review</a></li>
                                       
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-4">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Contact us</h4>
                                    <ul>
                                        <li><a href="#">consulto98@gmail.com</a></li>
                                        <li><a href="#">76/A, Green road, NYC</a></li>
                                        <li><a href="#">Privacy Policy</a></li>
                                        <li class="number"><a href="#">(80) 783 367-3904</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- footer-bottom area -->
            <div class="footer-bottom-area">
                <div class="container">
                    <div class="footer-border">
                        <div class="row d-flex align-items-center">
                            <div class="col-xl-12 ">
                                <div class="footer-copy-right text-center">
                                    <p>
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                        Copyright &copy;
                                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://nhiep.net" target="_blank">Nhiep.net</a>
                                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End-->
        </div>
    </footer>
    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>

    <!-- JS here -->

    <script src="~/assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="~/assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="~/assets/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="~/assets/js/owl.carousel.min.js"></script>
    <script src="~/assets/js/slick.min.js"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="~/assets/js/wow.min.js"></script>
    <script src="~/assets/js/animated.headline.js"></script>
    <script src="~/assets/js/jquery.magnific-popup.js"></script>

    <!-- Date Picker -->
    <script src="~/assets/js/gijgo.min.js"></script>
    <!-- Nice-select, sticky -->
    <script src="~/assets/js/jquery.nice-select.min.js"></script>
    <script src="~/assets/js/jquery.sticky.js"></script>
    <!-- Progress -->
    <script src="~/assets/js/jquery.barfiller.js"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="~/assets/js/jquery.counterup.min.js"></script>
    <script src="~/assets/js/waypoints.min.js"></script>
    <script src="~/assets/js/jquery.countdown.min.js"></script>
    <script src="~/assets/js/hover-direction-snake.min.js"></script>

    <!-- contact js -->
    <script src="~/assets/js/contact.js"></script>
    <script src="~/assets/js/jquery.form.js"></script>
    <script src="~/assets/js/jquery.validate.min.js"></script>
    <script src="~/assets/js/mail-script.js"></script>
    <script src="~/assets/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="~/assets/js/plugins.js"></script>
    <script src="~/assets/js/main.js"></script>


    <!--  <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>-->
    @RenderSection("ScriptsValidate", required: false)
</body>
</html>

QLSach/QLSach/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Tuan Le">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Quản Lý Sách </title>

    <!-- Fontfaces CSS-->
    <link href="~/assetsdash/css/font-face.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="~/assetsdash/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="~/assetsdash/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="~/assetsdash/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="~/assetsdash/css/theme.css" rel="stylesheet" media="all">

</head>
<body class="animsition">
    <div class="page-wrapper">
        <!-- HEADER MOBILE-->
        <header class="header-mobile d-block d-lg-none">
            <div class="header-mobile__bar">
                <div class="container-fluid">
                    <div class="header-mobile-inner">
                        <a class="logo" href="index.html">
                            <img src="images/icon/logo.png" alt="CoolAdmin" />
                        </a>
                        <button class="hamburger hamburger--slider" type="button">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="navbar-mobile">
                <div class="container-fluid">
                    <ul class="navbar-mobile__list list-unstyled">
                        <li>
                            <a asp-controller="Category" asp-action="Index">
                                <i class="fas fa-chart-bar"></i>Category
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Books" asp-action="Index">
                                <i class="fas fa-table"></i>Book
                            </a>
                        </li>



                    </ul>
                </div>
            </nav>
        </header>
        <!-- END HEADER MOBILE-->
        <!-- MENU SIDEBAR-->
        <aside class="menu-sidebar d-none d-lg-block">
            <div class="logo">
                <a href="#">
                    <img src="~/assetsdash/images/icon/logo.png" alt="Cool Admin" />
                </a>
            </div>
            <div class="menu-sidebar__content js-scrollbar1">
                <nav class="navbar-sidebar">
                    <ul class="list-unstyled navbar__list">

                        <li>
                            <a asp-controller="Category" asp-action="Index">
                                <i class="fas fa-chart-bar"></i>Category
                            </a>
                        </li>
                        <li>
                            <a asp-controller="Books" asp-action="Index">
                                <i class="fas fa-table"></i>Book
                            </a>
                        </li>




                    </ul>
                </nav>
            </div>
        </aside>
        <!-- END MENU SIDEBAR-->
        <!-- PAGE CONTAINER-->
        <div class="page-container">
            <!-- HEADER DESKTOP-->
            <header class="header-desktop">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">
                        <div class="header-wrap">
                            <div class="col-6"></div>
                            <div class="header-button">

                                <div class="account-wrap">
                                    <div class="account-item clearfix js-item-menu">
                                        <div class="image">

                                            <img src="~/assetsdash/images/icon/TuanAdmin.jpg" alt="Tuan Le" />
                                        </div>
                                        <div class="content">
                                            <a class="js-acc-btn" href="#">Tuan Le</a>
                                        </div>
                                        <div class="account-dropdown js-dropdown">
                                            <div class="info clearfix">
                                                <div class="image">
                                                    <a href="#">
                                                        <img src="~/assetsdash/images/icon/TuanAdmin.jpg" alt="Tuan Le" />
                                                    </a>
                                                </div>
                                                <div class="content">
                                                    <h5 class="name">
                                                        <a href="#">Tuan Le</a>
                                                    </h5>
                                                    <span class="email">levantuanpxu@gmail.com</span>
                                                </div>
                                            </div>

                                            <div class="account-dropdown__footer">
                                                <a asp-controller="Home" asp-action="Index">
                                                    <i class="zmdi zmdi-power"></i>Logout
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </header>

            <!-- HEADER DESKTOP-->


            <div class="main-content">
                <div class="container-fluid">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>




            <!-- Jquery JS-->
            <script src="~/assetsdash/vendor/jquery-3.2.1.min.js"></script>
            <!-- Bootstrap JS-->
            <script src="~/assetsdash/vendor/bootstrap-4.1/popper.min.js"></script>
            <script src="~/assetsdash/vendor/bootstrap-4.1/bootstrap.min.js"></script>
            <!-- Vendor JS       -->
            <script src="~/assetsdash/vendor/slick/slick.min.js"></script>
            <script src="~/assetsdash/vendor/wow/wow.min.js"></script>
            <script src="~/assetsdash/vendor/animsition/animsition.min.js"></script>
            <script src="~/assetsdash/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
            <script src="~/assetsdash/vendor/counter-up/jquery.waypoints.min.js"></script>
            <script src="~/assetsdash/vendor/counter-up/jquery.counterup.min.js"></script>
            <script src="~/assetsdash/vendor/circle-progress/circle-progress.min.js"></script>
            <script src="~/assetsdash/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
            <script src="~/assetsdash/vendor/chartjs/Chart.bundle.min.js"></script>
            <script src="~/assetsdash/vendor/select2/select2.min.js"></script>

            <!-- Main JS-->
            <script src="~/assetsdash/js/main.js"></script>


            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            @RenderSection("ScriptsValidate", required: false)
</body>
</html>